### ISSUE TITLE
curl error: Problem with the SSL CA cert (path access rights?)

### ISSUE THREAD

**Issue by kmanwar89** [archlinuxfr/yaourt#287]
Receive this error on a fresh Arch install when trying to install Google Chrome

**Comment by kmanwar89** [comment]
The issue was resolved by issuing `sudo update-ca-trust`, but why does the error exist in the first place?

**Comment by simonbcn** [comment]
I have the same problem now and `sudo update-ca-trust` doesn't solve the problem.

**Comment by moneroexamples** [comment]
Same problem here:

```
curl: (60) SSL certificate problem: self signed certificate in certificate chain
More details here: https://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
==> ERROR: Failure while downloading https://dist.torproject.org/torbrowser/6.0.8/tor-browser-linux64-6.0.8_en-US.tar.xz
    Aborting...
==> ERROR: Makepkg was unable to build tor-browser-en.

```

**Comment by leo-mao** [comment]
@moneroexamples try the following steps:
1. run ` curl-config` and you will get something, e.g. `/etc/ssl/certs/ca-certificates.crt`
2. go to [caExtract.html](https://curl.haxx.se/docs/caextract.html) download the latest `cacert.pem`, e.g. `cacert-2017-01-18.pem`
3. put & rename the latest `cacert.pem` to the path in the 1.step, e.g. `sudo mv cacert-2017-01-18.pem /etc/ssl/certs/ca-certificates.crt`
4. try to `yaourt  -S  tor-browser-en` again

**Comment by moneroexamples** [comment]
@leo-mao

Thanks. Its working now, so cant try that at the moment. Since January it must have been fixed.

**Comment by vampur** [comment]
@leo-mao 
Just ran into this problem today, and your solution worked perfectly. Thank you.

**Comment by leo-mao** [comment]
@vampur that will be great. I also tried other workarounds last time, but neither worked. Fortunately I figured this way out.



MfG
Yang Mao

**Comment by telis80** [comment]
nice one ty @leo-mao works under arch

**Comment by Bluedino549** [comment]
@leo-mao 
Thanks a lot! That solved my problems on both Arch and Manjaro!

**Comment by alt229** [comment]
Installing curl fixed this for me

**Comment by ElliotNB** [comment]
Just thought I'd add my two cents here since this page now shows prominently in Google when you search for the error message **curl error: Problem with the SSL CA cert (path access rights?)** 

In our case, we had this error displaying for PHP CURL but not command line CURL. All affiliated libraries had been updated (`openssl`, `nss`, `curl`, etc) as well as the suggestions made above (e.g., `sudo update-ca-trust`). We also restarted Apache, but to no effect.

We eventually had to restart the entire server. After the server came back online, the problem was fixed.

**Comment by leo-mao** [comment]
The entire server? That’s sad.

On 13 Mar 2018, at 5:11 PM, Elliot <notifications@github.com<mailto:notifications@github.com>> wrote:


Just thought I'd add my two cents here since this page now shows prominently in Google when you search for the error message curl error: Problem with the SSL CA cert (path access rights?)

In our case, we had this error displaying for PHP CURL but not command line CURL. All affiliated libraries had been updated (openssl, nss, curl, etc) as well as the suggestions made above (e.g., sudo update-ca-trust). We also restarted Apache, but to no effect.

We eventually had to restart the entire server. After the server came back online, the problem was fixed.

**Comment by Digdgeo** [comment]
leo-mao solution works for me. Thanks!
