### ISSUE TITLE
missing ability to sync_package when building from directory

### ISSUE THREAD

**Issue by mchataigner** [archlinuxfr/yaourt#292]
I am trying to install a custom PKGBUILD that depends on other AUR with:
`yaourt -Pi .`
And it throws me this
```
/usr/lib/yaourt/pkgbuild.sh: line 268: sync_packages: command not found
```
I don't know if this is a bug or a feature though.

Thanks for your help.

**Comment by mchataigner** [comment]
Hmm, sorry, there was a typo in the AUR dependency, works like a charm.

**Comment by larchunix** [comment]
I guess it's the same issue as #244. It has been fixed in #245.

Before a new release including this fix is out, you should use a version of yaourt built from git.

**Comment by mchataigner** [comment]
Hmmm, yes you are right. However, it is still not released.
Do you have any plans for it?
Thanks.
